// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {apperr} from '../models';

export function Libraries():Promise<Array<models.LibraryRoot>>;

export function ScanAssets(arg1:string):Promise<apperr.Result_Studio_internal_models_AssetScanResult_>;
