// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Libraries() {
  return window['go']['assetsservice']['AssetsService']['Libraries']();
}

export function ScanAssets(arg1) {
  return window['go']['assetsservice']['AssetsService']['ScanAssets'](arg1);
}
