// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NewProject(arg1) {
  return window['go']['projectservice']['ProjectService']['NewProject'](arg1);
}

export function OpenProject(arg1) {
  return window['go']['projectservice']['ProjectService']['OpenProject'](arg1);
}

export function SaveProject(arg1) {
  return window['go']['projectservice']['ProjectService']['SaveProject'](arg1);
}
