// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apperr} from '../models';
import {models} from '../models';

export function NewProject(arg1:string):Promise<apperr.Result_Studio_internal_models_Project_>;

export function OpenProject(arg1:string):Promise<apperr.Result_Studio_internal_models_Project_>;

export function SaveProject(arg1:models.Project):Promise<apperr.Result_Studio_internal_models_Project_>;
