// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDirectory() {
  return window['go']['main']['App']['ChooseDirectory']();
}

export function OpenProjectDialog() {
  return window['go']['main']['App']['OpenProjectDialog']();
}

export function SaveProjectDialog(arg1, arg2) {
  return window['go']['main']['App']['SaveProjectDialog'](arg1, arg2);
}
