// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apperr} from '../models';

export function ChooseDirectory():Promise<apperr.Result_string_>;

export function OpenProjectDialog():Promise<apperr.Result_string_>;

export function SaveProjectDialog(arg1:string,arg2:string):Promise<apperr.Result_string_>;
